### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by isoz** [ArufaTeam/Arufa#10]
I gave this a test run in one of my servers and players were complaining about some stuff.
They said they were dying with full hearts which suggests hearts were not updating in some cases and Some others said they couldn't respawn when they died and that it "glitches"
Also world loading time takes too long, "building terrain"

"I got oblit ,landed nothing happened the I couldn't hit anyone and it looked like I was invis then i kept getting hit I flew up the air I tried eat a gapple but didn't work then died and crashed"

"I just got killed in one hit with full prot 5 gear and each time that I die my body is stuck in place with all my hearts"

"It takes forever for me to load in when I try join nova"

"something is wrong with my pvp and whenever I die, I can't respawn and it glitches!"

**Comment by NFGamerMC** [comment]
We will look into this!

**Comment by TheRoyalBlock** [comment]
Question 1: `couldn't respawn when they died and that it "glitches"`
Answer 1: The glitch is a bug that was found long ago in pmmp

Question 2: `Also world loading time takes too long, "building terrain"`
Answer 2: The building terrain is because of multiple reasons. 1: The world is a large world with many chunks. 2: The server may be trying to load multiple worlds. 3: Slow connection. 4: Slow server

Question 3: `I got oblit ,landed nothing happened the I couldn't hit anyone and it looked like I was invis then i kept getting hit I flew up the air I tried eat a gapple but didn't work then died and crashed`
Answer 3: I really don't know, wait for AppleDevelops' response.

Question 4: `I just got killed in one hit with full prot 5 gear and each time that I die my body is stuck in place with all my hearts`
Answer 4: One hit with prot 5 gear? Ouch. Enchantments have been broken for a while, its a major project to fix and rewriting it is the easiest.

Question 5: `It takes forever for me to load in when I try join nova`
Answer 5: Same as question 2

Question 6: `something is wrong with my pvp and whenever I die, I can't respawn and it glitches!`
Anwer 6: Same as question 1.

**Comment by isoz** [comment]
That's great. But I don't own a small server and with all other forks none of those problems happen so if you don't have nothing to add please refrain from commenting. I'm here trying to help, unfortunately it seems all spoons are plagued with 12 year olds wanna be coders on their phones.

**Comment by NFGamerMC** [comment]
So, if you think that we are 12 year olds that can't code then fix the problem yourself because apparently "We cannot Code!". Go to something else if you are just going to complain

**Comment by isoz** [comment]
Most of you are. I'm not sure about you specifically but I was referring to the comment above that was discrediting my attempt on trying to report the problems. I was mostly referring to the fact that everyone that offers help is accepted.

**Comment by NFGamerMC** [comment]
Nope, only 6 developers have been added. @TheRoyalBlock was not added he was trying to help. We will try to fix your issue ASAP

**Comment by AppleDevelops** [comment]
1) Partially fixed
2) Building Terrain depends on the amount of chunks and connection
3) Not sure on this
4) Stupid bug which is part of 1, and will be committed later
5) With sounds added it will be a blank screen and will take some time to connect now. 
6) Part of 1 and 4

**Comment by AppleDevelops** [comment]
I'm afraid your assumptions are mostly correct about spoons, @isoz. Luckily I'm not 12 and hate coding on my phone.

**Comment by isoz** [comment]
That's great,  apple. It baffles me how anyone claims to be a developer but never owned a computer. I'm sure they have great minds but the hardware surely limits them.

**Comment by TheRoyalBlock** [comment]
Nobody ever said that that were a developer and they didn't have computers. Also, I am not 12.

**Comment by daniktheboss** [comment]
Royalblock, please just stfu. Your making yourself look even more stupid. Look at me I'm probably as good as apple but never comment shit unless really needed.
